spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/formacion?serverTimezone=UTC
    username: root
    password: TfJ^AGC8eGW*
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: 192.168.56.1
    non-secure-port: 8081
